apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-dynamic-volume-claim
spec:
  storageClassName: "lab"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
